# Generated by Django 3.2.5 on 2026-04-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(error_messages={'id_number': 'A user with ID already exists.'}, max_length=250, unique=True),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('husband', 'Husband'), ('wife', 'Wife'), ('father', 'Father'), ('mother', 'Mother'), ('son', 'Son'), ('daughter', 'Daughter'), ('sibling', 'Sibling')], max_length=20)),
                ('client_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='client.client')),
                ('client_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='client.client')),
            ],
            options={
                'unique_together': {('client_from', 'client_to')},
            },
        ),
    ]
